apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deploy
  namespace: ns-2
  labels:
    app: app-1-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: container-name-1
        image: vietaws/eks:v1
        ports:
        - containerPort: 8080
