apiVersion: v1
kind: Pod
metadata:
  name: simple-app-2
  namespace: demo
spec:
  containers:
  - name: container-name-1
    image: vietaws/eks:v1
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        # cpu: "1000m"  # Recommend don't set cpu limit 
       
    ports:
    - containerPort: 8080

