apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-1
  labels:
    app: rs-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: simple-app
        image: vietaws/eks:v3
        ports:
        - containerPort: 8080

